### ISSUE TITLE
start_urls or SgmlLinkExtractor for pagination seem to be ignored

### ISSUE THREAD

**Issue by flamby** [ssteuteville/scrapyz#1]
Hi,
First of all, thanks a lot for this lib which avoid me a lot of boilerplate code w/ scrapy.

Maybe i missed something, but it seems multiple start_urls are ignored w/ IndexDetailSpider.
I see the retrieving of all start_urls but then, only the first one is crawled for detail_targets.

Are you aware of that?

As an idea of Feature Request, you could add to scrapyz a lot of convenient "transform" functions like you did w/ your join function.

Thanks.

**Comment by ssteuteville** [comment]
Thanks for the feedback. The problem is here:

https://github.com/ssteuteville/scrapyz/blob/7050f7e2ec231cf44198da4a3cd840116bc31739/scrapyz/core.py#L78

This is how I intended for it to work but I think what you want it to do is a good idea.

If you want to make a pull request that treats Meta.detail_path as a list of Targets I'll merge it in for you.

Otherwise I'll do it myself when I get a chance.

As for your feature request, that is a plan of mine. If you want anything specific please feel free to create PR or issues (adding the label 'Feature Request').
